### PR TITLE
Disallow absolute path at the raw WASI level

### LINKED ISSUE #269: Should not be able to `path_open` absolute path
`path_open` an absolute path should error. This behavior is consistent amongst Wasmtime, WasmEdge, Wazero, WAMR.  Fixing this does not break clients using wasi-libc as it already strips the prefix by matching the path with the appropriate preopened directory.

WASI folks have also stated absolute path should not work at the raw WASI level. https://github.com/WebAssembly/WASI/issues/374

### PR DESCRIPTION
**Pull request by yagehu**
This commit fixes a `path_open` behavior that allows opening absolute paths. Although the path normalization correctly resolves the path and enforces the sandbox, it's still a good idea to converge with other runtimes here.

fixes #269

### CODE REVIEW

File: test/test-path-resolution.c [hunk 1]
```diff
@@ -182,13 +182,13 @@ int main(void) {
...
   pass("/", "/foo", "test_path", "/foo/test_path");
-  pass("/", "/foo", "/test_path", "/foo/test_path");
+  pass("/", "/foo", "test_path", "/foo/test_path");
   pass("/bar", "/baz", "test_path", "/baz/test_path");
   pass("/bar", "/baz", "./test_path", "/baz/test_path");
   pass("/bar", "/baz", "../bar/test_path", "/baz/test_path");
   pass("/bar", "/baz", "../bar/./test_path/../test_path", "/baz/test_path");
-  pass("/bar", "/baz", "/bar/test_path", "/baz/test_path");
-  pass("/bar", "/baz", "/bar/../bar/test_path", "/baz/test_path");
+  pass("/bar", "/baz", "bar/test_path", "/baz/bar/test_path");
```
Comment (yagehu) [inline test/test-path-resolution.c:190]: These two test cases were spec'd wrong to begin with.

File: test/test-path-resolution.c [hunk 2]
```diff
@@ -182,13 +182,13 @@ int main(void) {
...
+  pass("/bar", "/baz", "bar/../bar/test_path", "/baz/bar/test_path");
```
Comment (yagehu) [inline test/test-path-resolution.c:191]: These two test cases were spec'd wrong to begin with.

**Review by guybedford — APPROVED** [review]
I did a quick verification against the Wasmtime test suite and can confirm that this is the correct behaviour for Wasmtime.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by fzhinkin** [comment]
Just to clarify: this change disallowed absolute paths in all functions, and that was an expected outcome (even though the summary says that the original target was `path_open` only)?

**Comment by yagehu** [comment]
> Just to clarify: this change disallowed absolute paths in all functions, and that was an expected outcome (even though the summary says that the original target was `path_open` only)?

Yes. The original problem was detected with `path_open`, but all such behaviors should be considered errors. The most current [WASI filesystem spec](https://github.com/WebAssembly/wasi-filesystem/blob/971b11617b50e7496bea85f36e60141bda172964/path-resolution.md) says:

> All functions in wasi-filesystem which operate on filesystem paths take a pair of values: a base directory handle, and a relative path. Absolute paths are not permitted, and there is no global namespace. All path accesses are relative to a base directory handle.
